version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}
    ports:
      - "5433:5432"  # He cambiado el puerto del host a 5433 para evitar conflictos
    volumes:
      - ./postgres:/var/lib/postgresql/data